-- MySQL Script generated by MySQL Workbench
-- 08/23/15 12:40:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbtarefadecasa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbtarefadecasa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbtarefadecasa` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dbtarefadecasa` ;

-- -----------------------------------------------------
-- Table `dbtarefadecasa`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtarefadecasa`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL COMMENT 'O email é usado para o login do usuário.',
  `senha` VARCHAR(32) NOT NULL,
  `tipo` TINYINT(2) NOT NULL DEFAULT 1 COMMENT 'Esta é a identificação do tipo de usuário\n1 - Usuário do tipo aluno.\n2 - Usuário do tipo professor.\n3 - Administrador',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtarefadecasa`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtarefadecasa`.`disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `notificacao` TINYINT(1) NULL COMMENT 'Notificar quando existir tarefa relacionada a esta disciplina.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtarefadecasa`.`tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtarefadecasa`.`tarefa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_disciplina` INT NOT NULL,
  `tipo` TINYINT(2) NOT NULL DEFAULT 1,
  `id_professor` INT NOT NULL COMMENT 'Identificação do professor, usuário que está aplicando a tarefa em questão.',
  PRIMARY KEY (`id`),
  INDEX `fk_trf_disciplina_idx` (`id_disciplina` ASC),
  INDEX `fk_trf_usuario_idx` (`id_professor` ASC),
  CONSTRAINT `fk_trf_disciplina`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `dbtarefadecasa`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trf_usuario`
    FOREIGN KEY (`id_professor`)
    REFERENCES `dbtarefadecasa`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtarefadecasa`.`disciplina_inscrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtarefadecasa`.`disciplina_inscrito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_disciplina` INT NOT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_disciplina_UNIQUE` (`id_disciplina` ASC),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  CONSTRAINT `fk_di_disciplina`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `dbtarefadecasa`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_di_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dbtarefadecasa`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
